#!/usr/bin/env ruby

$LOAD_PATH.unshift './lib'

require 'brain'
require 'thor'

class Cli < Thor
  desc 'explore', 'Interactively explore the brain'
  def explore
    knowledge = Brain.acquire_knowledge!
    cortex = Brain::Context::Cortex.new knowledge

    Brain::Cli.start_session cortex
  end

  no_commands do
  end
end

Cli.start ARGV
